import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Header from "@/components/Header";
import Banner from "@/components/Banner";
import Produtos from "@/components/Produtos";
import Sobre from "@/components/Sobre";
import Contato from "@/components/Contato";


export default function Home() {
  return (
    <>
      <Head>
        <title>Scent | Perfumaria</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

      </Head>      

    <Header/>
      <section>
        <Banner/>
      </section>
    
      <section>
        <Produtos/>
      </section>

      <section>
        <Sobre/>
      </section>

      <section>
        <Contato/>
      </section>
    </>
  );
}
